version: '3'

services:
  frontend:
    build: frontend
    container_name: schwering_app_light_frontend
    restart: unless-stopped
    ports:
      - 10001:80

  backend:
    build: backend
    container_name: schwering_app_light_backend
    env_file: .env
