version: '3'

services:
  frontend:
    build: frontend
    container_name: schwering_app_light_frontend
    ports:
      - 80:80
    networks:
      macvlan:
        ipv4_address: 10.16.1.2
      default:

  backend:
    build: backend
    container_name: schwering_app_light_backend
    env_file: .env

networks:
  macvlan:
    driver: macvlan
    driver_opts:
      parent: eth0
    ipam:
      config:
        - subnet: 10.16.1.2/32
          
