version: '3'

services:
  frontend:
    # build: frontend
    image: ghcr.io/dliebg/schwering_app_light_frontend/frontend:main
    container_name: schwering_app_light_frontend
    restart: unless-stopped
    ports:
      - 10001:80

  backend:
    # build: backend
    image: ghcr.io/dliebg/schwering_app_light_frontend/backend:main
    container_name: schwering_app_light_backend
    restart: unless-stopped
    env_file: .env

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: schwering_app_light_frontend schwering_app_light_backend -i 3600
